# TODO: when removing v1beta, delete the file
version: '2.4'
services:
  graphiql:
    image: pokeapi/graphiql:v1beta-2.1.0
  web:
    volumes:
      - ./Resources/nginx/nginx-gql-v1beta.conf:/etc/nginx/nginx.conf:ro
      - ./Resources/nginx/ssl:/ssl:ro
      - graphql_cache:/tmp/cache