version: '2.4'
services:
  cache:
    image: redis:7.4.2-alpine3.21
    volumes:
      - redis_data:/data
    restart: always

  app:
    user: ${RUN_AS:-pokeapi}
    env_file: .env
    volumes:
      - .:/code
    links:
      - cache
    depends_on:
      cache:
        condition: service_started
    restart: always

  web:
    image: nginx:1.27.3-alpine3.20
    ports:
      - "16680:80"
    restart: always
    # command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./Resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Resources/nginx/ssl:/ssl:ro
      - graphql_cache:/tmp/cache
  graphql-engine:
    image: hasura/graphql-engine:v2.48.1
    env_file: .env   
    ports:
      - "16681:8080"
    restart: always

volumes:
  redis_data:
  graphql_cache:
